version: "3.7"
services:
  server:
    image: nginx:latest
    container_name: nginx_resume
    restart: always
    ports:
      - 127.0.0.1:2400:80
    volumes:
    - /mnt/hdd0/resume:/var/www
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
